# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install python's dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install rdflib
    - name: Install robot
      run: |
        sudo wget --no-verbose -m -nH -nd -P /usr/bin https://raw.githubusercontent.com/ontodev/robot/master/bin/robot
        sudo wget --no-verbose -m -nH -nd -P /usr/bin https://github.com/ontodev/robot/releases/latest/download/robot.jar
        sudo chmod +x /usr/bin/robot
    - name: Merge ontologies with robot
      run: |
        robot merge --input AboutIDMPDev.rdf --output AboutIDMPDevMerged.ttl --catalog /home/runner/work/idmp/idmp/catalog-v001.xml
    - name: Run comptency questions using rdflib
      run: |
        python etc/cq_runner.py --folder_with_competency_questions etc/CQ/Example \
          --ontology_path /home/runner/work/idmp/idmp/AboutIDMPDevMerged.ttl
        if [ $? != 0 ];
        then
        exit $?
        fi
